version: '3'
services:
  web:
    image: nginx:latest
    container_name: app-web
    volumes:
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/html:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - app_default
    restart: always

networks:
  app_default:
    driver: bridge
